---
title: "Module 02 - The Input Output Model"
author: "Renato Vargas"
date: "6/20/2018"
output:
  ioslides_presentation: default
  slidy_presentation: default
  beamer_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Fundamental relationships

We categorize the economy in _n_ sectors. $x_i$ is the total output of sector $i$ and $f_i$ is the total demand for sector $i$'s product. So sales of this sector to other sectors and final demand for all n sectors can be expressed as:

$$
\begin{equation}
x_j=z_{11}+\cdots+z_{1j}+\cdots+z_{1n}+f_i
\end{equation}
$$
$$
\begin{equation}
x_j=z_{i1}+\cdots+z_{ij}+\cdots+z_{in}+f_i
\end{equation}
$$
$$
\begin{equation}
x_j=z_{n1}+\cdots+z_{nj}+\cdots+z_{nn}+f_i
\end{equation} 
$$

## Compact representation


$$\begin{equation} \mathbf{x} = \begin{bmatrix} \begin{array}{c} x_1 \\ \vdots\\ x_n\\ \end{array} \end{bmatrix} \mathbf{Z} = \begin{bmatrix}\begin{array}{ccc} z_{11} & \ldots & z_{1n} \\ \vdots &  \ddots &  \\ z_{n1} &  & z_{nn} \end{array} \end{bmatrix} \mathbf{f}= \begin{bmatrix} \begin{array}{c} f_{1} \\ \vdots  \\ f_{n} \end{array} \end{bmatrix}\end{equation}$$

<center>
or 

$\mathbf{x} = \mathbf{Zi} + \mathbf{f}$
</center>
<br>
<br>
We need to multiply by the summation column vector $\mathbf{i}$ of 1's of dimension n.

## Input-output coefficient

Given $z_{ij}$ and $x_j$, for example input of boat fuel ($i$) bought by small-scale fishers ($j$) last year and total fishers production last year -  form the ratio of fuel of fuel to fishers output, $z_{ij}/x_{j}$, (both units in currency) and denote it $a_{ij}$.

Consequently, direct input (technical) coefficients can be defined as 

$$a_{ij} = \frac{z_{ij}}{x_j}$$

This ratio is called a technical coefficient, input-output coefficient, or direct input coefficient.

## Coefficients for all sectors

We have that $\mathbf{x} = \mathbf{Zi} + \mathbf{f}$.

We know that a hat over a vector $\mathbf{\hat{x}}$ yields a matrix with the vector along its diagonal.

We know that $(\mathbf{\hat{x}})(\mathbf{\hat{x}})^{-1} = \mathbf{I}$ so it follows that $\mathbf{\hat{x}}^-1$

Therefore the n x n matrix of technical coefficients can be represented as

$$\mathbf{A} = \mathbf{Z}\mathbf{\hat{x}}^{-1}$$

## The input-output model

Then from our definition of matrices and $\mathbf{A} = \mathbf{Z}\mathbf{\hat{x}}^{-1}$ it follows that:

$$\mathbf{x}=\mathbf{Ax} + \mathbf{f}$$

And from matrix algebra we know that I is an identity matrix so:

$$(\mathbf{I} - \mathbf{A})\mathbf{x} = \mathbf{f}$$

So to solve for x:

$$\mathbf{x}=(\mathbf{I}-\mathbf{A})^{-1} \mathbf{f} = \mathbf{L}\mathbf{f}$$

Where $(\mathbf{I}-\mathbf{A})^{-1} \mathbf{f} = \mathbf{L}$ is known as the Leontief inverse or the total requirements matrix.

